openapi: "3.0.0"
info:
  title: Guestbook API Gateway
  version: 1.0.0

x-yc-apigateway:
  cors:
    origin: '*'
    methods: '*'
    allowedHeaders: '*'

paths:
  /api/{proxy+}:
    x-yc-apigateway-any-method:
      operationId: proxyToContainer
      parameters:
        - name: proxy
          in: path
          required: false
          schema:
            type: string
      x-yc-apigateway-integration:
        type: serverless_containers
        container_id: REPLACE_CONTAINER_ID
        service_account_id: REPLACE_SA_ID

  /:
    get:
      operationId: getIndex
      x-yc-apigateway-integration:
        type: object_storage
        bucket: REPLACE_BUCKET_NAME
        object: index.html
        service_account_id: REPLACE_SA_ID

  /{file}:
    get:
      operationId: getStaticFile
      parameters:
        - name: file
          in: path
          required: true
          schema:
            type: string
      x-yc-apigateway-integration:
        type: object_storage
        bucket: REPLACE_BUCKET_NAME
        object: '{file}'
        service_account_id: REPLACE_SA_ID
